
import json

tools = [{
    'type': 'function',
    'function': {
        'name': 'image_zoom_in_tool',
        'description': 'Zoom in on a specific region of an image by cropping it based on a bounding box (bbox) and an optional object label',
        'parameters': {
            'type': 'object',
            'properties': {
                'bbox_2d': {
                    'type': 'array',
                    'items': {'type': 'number'},
                    'minItems': 4,
                    'maxItems': 4,
                    'description': 'The bounding box of the region to zoom in, as [x1, y1, x2, y2], where (x1, y1) is the top-left corner and (x2, y2) is the bottom-right corner'
                },
                'object': {
                    'type': 'string',
                    'description': 'The object name or label of the object in the specified bounding box'
                }
            },
            'required': ['bbox_2d', 'label']
        }
    }
}]

test_system = """

"""

to_itm_data = {
  "tools": json.dumps(tools,ensure_ascii=False),
  "messages": [
    {"role": "user", "content": "<image>This is a image, which might be taken from real world or generated by an advanced AI model. \nIs this image generated by an AI model? (Answer fake if you think it is synthesized by an AI model, and answer real otherwise.)"},
    {"role": "assistant", "content": "<think>\n我可以通过打开日历App来获取当前时间。\n</think>\n"},
    {"role": "tool_call", "content": "{\"name\": \"image_zoom_in_tool\", \"arguments\": {\"bbox_2d\": <bbox>, \"label\": \"<ref-object>\"}\n}"},
    {"role": "tool_response", "content": "{\"images\": \"<image>\", \"status\": \"success\"}"},
    {"role": "assistant", "content": "<think>\nIn the current crop, I can now see a small white dog walking on the sidewalk near the people. The dog appears to be white in color. Since I can now clearly see the dog and determine its color, I can provide the answer to the question. The dog is white, which corresponds to option D (Black and white) if we consider white as one of the colors in the black and white combination.\n</think>\n<answer> fake </answer>"}
  ],
  "objects": {"ref": [], "bbox": []},
  "images": []
}

# 保存为 JSON 文件
with open("./tools_config.json", "w", encoding="utf-8") as f:
    json.dump(to_itm_data, f, ensure_ascii=False, indent=2)

print("Saved to tools_config.json")